name: Release

permissions:
  # To create the follow-up PR.
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Pulumi override verison to release

concurrency: release

jobs:
  release:
    name: release
    uses: ./.github/workflows/release.yml
    with:
      ref: ${{ github.ref }}
      version: ${{ inputs.version }}
      release-notes: Releasing version ${{ inputs.version }}
      queue-merge: true
      run-dispatch-commands: true
    secrets: inherit
